---
    -   name: Create Network Security Group
        azure_rm_securitygroup:
            resource_group: "{{ resource_group }}"
            name: "{{ item.name }}-sg"
            purge_rules: yes
            rules:
            -   name: SSH
                protocol: Tcp
                destination_port_range: 22
                access: Allow
                priority: 1001
                direction: Inbound
            -   name: HTTP
                protocol: Tcp
                destination_port_range: 80
                access: Allow
                priority: 1002
                direction: Inbound
            -   name: HTTPS
                protocol: Tcp
                destination_port_range: 443
                access: Allow
                priority: 1003
                direction: Inbound
            -   name: APP_Port
                protocol: Tcp
                destination_port_range: 5000
                access: Allow
                priority: 1004
                direction: Inbound
            -   name: MySQL
                protocol: Tcp
                destination_port_range: 3306
                access: Allow
                priority: 1005
                direction: Inbound
            tags: "{{ vmtags }}"