version: 2.1
executors:
  docker-publisher:
    environment:
      FLASK_ENV: production
      FLASK_APP: microblog.py
      IMAGE_NAME: mabn17/devops-v2-azure-test_prod
      CI_IMAGE_NAME: project_prod
      COMPOSE_COMMAND: prod
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    machine: true
    working_directory: ~/repo
    environment:
      FLASK_ENV: test
      FLASK_APP: microblog.py
    steps:
      - checkout
      - run:
          name: Linting dockerfiles, code and runs the tests.
          command: make test
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building the production image for Docker.
          command: docker-compose up --build -d $COMPOSE_COMMAND
      - run:
          name: Renaming or tagging the Docker image.
          command: docker tag $CI_IMAGE_NAME:latest $IMAGE_NAME:latest
      - run:
          name: Archiving the Docker image for later jobs.
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Loading the archived image.
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish the Docker image to Docker-hub.
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME
  update-app-server:
    executor: docker-publisher
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Installing venv.
          command: sudo apt-get install libpcap-dev libpq-dev python3-venv
      - run:
          name: Source the activate file.
          command: python3 -m venv venv
      - run: echo "source ~/project/venv/bin/activate" >> $BASH_ENV
      - run:
          name: Installing requirements to deploy the application.
          command: make install-deploy
      - run:
          name: Preparing the password decryption -file.
          command: echo "$VALUT_PASS" > ~/project/ansible/.vault_password.txt
      - run:
          name: Decrypt ansible variables and updates the AppServer.
          command: cd ansible && ansible-playbook gather_instances.yml update_instances.yml --vault-password-file .vault_password.txt

workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]++.[0-9]++.[0-9]++$/
            branches:
              ignore: /.*/
      - publish-latest:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]++.[0-9]++.[0-9]++$/
            branches:
              ignore: /.*/
      - update-app-server:
          requires:
            - publish-latest
          filters:
            tags:
              only: /^v[0-9]++.[0-9]++.[0-9]++$/
            branches:
              ignore: /.*/
